name: AreaPvP
version: ${project.version}
main: tokyo.peya.plugins.areapvp.AreaPvP
load: POSTWORLD
softdepend: ["EazyNick"]
depend: ["Vault"]
commands:
  areapvp:
  spawn:
    aliases: ["respawn"]
  oof:
  pvpd:
    aliases: ["debug", "pitdebug", "pdb"]
  view: