name: AreaPvP
version: ${project.version}
main: xyz.areapvp.areapvp.AreaPvP
loadbefore: ["Vault", "EazyNick"]
softdepend: ["EazyNick"]
commands:
  areapvp:
  spawn:
    aliases: ["respawn"]
  oof:
  pvpd:
    aliases: ["debug", "pitdebug", "pdb"]
  view: